# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'DynamicTableViewContent' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DynamicTableViewContent

	pod 'Alamofire', '4.8.0'
	pod 'SDWebImage', '~> 4.0'
    pod 'NVActivityIndicatorView'

  target 'DynamicTableViewContentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DynamicTableViewContentUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
